### ISSUE TITLE
Unable to run app after adding today widget

### ISSUE THREAD

**Issue by rajanshahsa** [DavidStrausz/cordova-plugin-today-widget#3]
Hello @DavidStrausz 

I had followed all the step you mention expect 'Enable the App Groups entitlement'. Now after running `cordova platform add ios`, I am able to add the widget to my project. But after that I am not able to run it. Every time I run the project it gives me the error.
![screen shot 2017-09-28 at 12 41 18 pm](https://user-images.githubusercontent.com/25100528/30953628-5d41fe9e-a44a-11e7-8709-13b73af7eb46.png)

I had removed the widget from "Embedde Binaries" after removing it, Project run successfully.

Please let me know what should I do to make the app working.

Thanks,
Rajan

**Comment by DavidStrausz** [comment]
Hi there, thanks for opening an issue!
So where do you have problems exactly, with the app group entitlements or in general with your widget?

I have never seen the error you posted so I did a quick google search and mostly the problem was "wired" characters somewhere in the naming of the app/widget. Please do the same and try a few of the suggested solutions.

BR
David

**Comment by rajanshahsa** [comment]
Hello @DavidStrausz ,

Sorry for the late reply. The problem solved. It was not working because widget not installed properly due to space in the name of the folder. I renamed the folder now its works perfectly.

Thanks,
Rajan
